// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table rasptb (messageId:long, EventProcessedUtcTime:datetime, EventEnqueuedUtcTime:datetime, rounded_temp:dynamic, rounded_humidity:dynamic, temperature:dynamic, humidity:dynamic) 
.create-merge table spintb (EventProcessedUtcTime:datetime, EventEnqueuedUtcTime:datetime, spin:dynamic) 
